//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXAudioJitterBufferReportInfo : NSObject
{
    int _loadTime;
    int _loadCnt;
    int _loadMaxTime;
    int _speedCnt;
    int _noDataCnt;
}

@property(nonatomic) int noDataCnt; // @synthesize noDataCnt=_noDataCnt;
@property(nonatomic) int speedCnt; // @synthesize speedCnt=_speedCnt;
@property(nonatomic) int loadMaxTime; // @synthesize loadMaxTime=_loadMaxTime;
@property(nonatomic) int loadCnt; // @synthesize loadCnt=_loadCnt;
@property(nonatomic) int loadTime; // @synthesize loadTime=_loadTime;
- (id)init;

@end

