//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXIPlayer.h"

#import "TXIAudioPlayDelegate.h"
#import "TXIDownloaderDelegate.h"
#import "TXINotifyDelegate.h"
#import "TXIVideoDecoderDelegate.h"
#import "TXIVideoJitterBufferDelegate.h"

@class NSString, TXCAudioPlayer, TXCRenderView, TXCStreamDownloader, TXCVideoDecoder, TXCVideoJitterBuffer, TXLivePlayerStatsCollection;

@interface TXCLivePlayer : TXIPlayer <TXIDownloaderDelegate, TXIVideoJitterBufferDelegate, TXIVideoDecoderDelegate, TXIAudioPlayDelegate, TXINotifyDelegate>
{
    TXCStreamDownloader *_streamDownloader;
    TXCVideoJitterBuffer *_videoJitterBuffer;
    TXCAudioPlayer *_audioPlayer;
    TXCRenderView *_renderView;
    TXLivePlayerStatsCollection *_playerStats;
    NSString *_playUrl;
    _Bool _isPlaying;
    TXCVideoDecoder *_videoDecoder;
}

@property(retain) TXCVideoDecoder *videoDecoder; // @synthesize videoDecoder=_videoDecoder;
- (void).cxx_destruct;
- (void)onNotifyEvent:(int)arg1 withParams:(id)arg2;
- (void)onDecodeFrame:(struct opaqueCMSampleBuffer *)arg1 FrameType:(long long)arg2 FrameIndex:(unsigned long long)arg3 ErrorCode:(unsigned long long)arg4;
- (void)onNALAvaliable:(id)arg1;
- (long long)onRequestAudioBufferDuration;
- (void)onPlayPcmData:(id)arg1;
- (void)onPullNAL:(id)arg1;
- (void)onPullAudio:(id)arg1;
- (void)onAppDidBecomeActive:(id)arg1;
- (void)onAppWillEnterForeground:(id)arg1;
- (void)onAppDidEnterBackGround:(id)arg1;
- (void)onAppWillResignActive:(id)arg1;
- (void)snapshot:(CDUnknownBlockType)arg1;
- (void)decodeNAL:(id)arg1;
- (void)setMute:(_Bool)arg1;
- (void)stopPlay;
- (int)startPlay:(id)arg1;
- (void)removeVideoWidget;
- (void)insertVideoWidgetToView:(id)arg1 atIndex:(long long)arg2;
- (_Bool)isPlaying;
- (void)setConfig:(id)arg1;
- (void)setupRealTimePlayParams;
- (void)releaseDecoder;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

