//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject, NSString;

@protocol TXIModule <NSObject>
- (NSObject *)statusValueForKey:(long long)arg1;
- (_Bool)setStatusValue:(NSObject *)arg1 forKey:(long long)arg2;
- (NSString *)getID;
- (void)clearID;
- (void)setID:(NSString *)arg1;
@end

