//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXIVideoEncoder : NSObject
{
    id <TXIVideoEncoderDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
    long long _realFPS;
    long long _encodeFrameCount;
    long long _bitrate;
}

@property(nonatomic, getter=realBitrate) long long bitrate; // @synthesize bitrate=_bitrate;
@property(readonly, nonatomic) long long encodeFrameCount; // @synthesize encodeFrameCount=_encodeFrameCount;
@property(readonly, nonatomic) long long realFPS; // @synthesize realFPS=_realFPS;
@property __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
@property __weak id <TXIVideoEncoderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)pushSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 timestamp:(unsigned long long)arg2;
- (long long)stop;
- (long long)startWith:(struct tagTXSVideoEncoderParam *)arg1;
- (void)sendNotifyEvent:(int)arg1;
- (id)init;

@end

