//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TXIStatsCollection.h"

@class NSLock, NSMutableDictionary, NSObject<OS_dispatch_source>, NSString, TXCAudioPlayer, TXCRenderView, TXCVideoJitterBuffer;

@interface TXLivePlayerStatsCollection : NSObject <TXIStatsCollection>
{
    double _collectInterval;
    NSObject<OS_dispatch_source> *_timer;
    NSMutableDictionary *_stats;
    NSMutableDictionary *_fix;
    NSMutableDictionary *_last;
    long long _lastTimestamp;
    long long _lastNotify;
    long long _lastReport;
    int _statusReportInterval;
    NSLock *_lock;
    _Bool _isCollecting;
    _Bool _isReportBeginEvt;
    long long _lastBlockCount;
    long long _firstIFrameRender;
    unsigned long long _startTime;
    int _maxVideoCache;
    int _sumVideoCache;
    int _numVideoCache;
    _Bool _realTimeMode;
    _Bool _isp2p;
    id <TXIDownloader> _downloader;
    TXCRenderView *_render;
    TXCVideoJitterBuffer *_jitter;
    TXCAudioPlayer *_audioPlayer;
    id <TXINotifyDelegate> _delegate;
    NSString *_url;
}

@property(nonatomic) _Bool isp2p; // @synthesize isp2p=_isp2p;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) _Bool realTimeMode; // @synthesize realTimeMode=_realTimeMode;
@property(nonatomic) __weak id <TXINotifyDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak TXCAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(nonatomic) __weak TXCVideoJitterBuffer *jitter; // @synthesize jitter=_jitter;
@property(nonatomic) __weak TXCRenderView *render; // @synthesize render=_render;
@property(nonatomic) __weak id <TXIDownloader> downloader; // @synthesize downloader=_downloader;
- (void).cxx_destruct;
- (void)reportRealTimePlayStatisticInfo;
- (void)setupStats;
- (long long)updateField:(id)arg1 value:(long long)arg2;
- (void)updateLoadInfo:(id)arg1;
- (void)updateNetStats:(id)arg1 interval:(long long)arg2;
- (void)updateRenderStats:(id)arg1 interval:(long long)arg2;
- (id)getSubStats;
- (void)collectStatus;
- (id)getStringFromNumber:(id)arg1;
- (id)getStringFromValue:(long long)arg1;
- (void)reportStatus;
- (void)reportEnd;
- (void)reportBegin;
- (void)reportFailed;
- (long long)getValueByKey:(id)arg1;
- (id)getStats;
- (void)stop;
- (void)startWithInteral:(double)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

