//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMComponent.h"

@class AttributeLabel, MMUIImageView;

@interface MMFavVoiceComponent : MMComponent
{
    AttributeLabel *_nameLabel;
    MMUIImageView *_iconView;
}

+ (double)calHeightWithComData:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getIconView;
- (void)setHighlightWord:(id)arg1 Detail:(id)arg2;
- (void)configVoiceView;
- (void)configContentLayout;

@end

