//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WAGameWhatsNewLoadingViewController, WALoadingViewController;

@interface WAAppTaskLoadingViewInfo : NSObject
{
    WALoadingViewController *_loadingVC;
    WAGameWhatsNewLoadingViewController *_whatsNewGameLoadingVC;
}

@property(retain, nonatomic) WAGameWhatsNewLoadingViewController *whatsNewGameLoadingVC; // @synthesize whatsNewGameLoadingVC=_whatsNewGameLoadingVC;
@property(retain, nonatomic) WALoadingViewController *loadingVC; // @synthesize loadingVC=_loadingVC;
- (void).cxx_destruct;

@end

