//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSObject<WAAudioSource>;

@protocol WAAudioSourceDelegate <NSObject>
- (void)sourceDidFinishPlaying:(NSObject<WAAudioSource> *)arg1;
- (void)sourceDidError:(NSObject<WAAudioSource> *)arg1 error:(NSError *)arg2;
- (void)sourceSeeked:(NSObject<WAAudioSource> *)arg1;
- (void)sourceSeeking:(NSObject<WAAudioSource> *)arg1;
- (void)sourceStop:(NSObject<WAAudioSource> *)arg1;
- (void)sourcePaused:(NSObject<WAAudioSource> *)arg1;
- (void)sourceStartPlaying:(NSObject<WAAudioSource> *)arg1;
@end

