//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WAAudioSource.h"

@class NSString, NSTimer, WAOpenALBuffer;

@interface WAAudioSourceOpenAL : NSObject <WAAudioSource>
{
    NSString *path;
    unsigned int sourceId;
    WAOpenALBuffer *buffer;
    _Bool looping;
    NSTimer *endTimer;
    float _duration;
    id <WAAudioSourceDelegate> _delegate;
}

@property(nonatomic) __weak id <WAAudioSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (void)ended:(id)arg1;
@property(nonatomic) float currentTime;
- (void)setPlaybackRate:(float)arg1;
- (void)setVolume:(float)arg1;
- (void)setLooping:(_Bool)arg1;
- (void)seek:(double)arg1;
- (void)stop;
- (void)pause;
- (void)play;
- (void)dealloc;
- (id)initWithPath:(id)arg1 filData:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

