//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "IWALocalCacheMgrExt.h"
#import "MMResourceMgrExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSString, WAInfoData, WAPackagePredownloadInfo;

@interface WAPackagePredownloadMgr : MMService <PBMessageObserverDelegate, IWALocalCacheMgrExt, IMsgExt, MMResourceMgrExt, MMService>
{
    _Bool _hasDownload;
    WAPackagePredownloadInfo *_packagePredownloadInfo;
    WAInfoData *_downloadingAppInfoData;
}

@property(retain, nonatomic) WAInfoData *downloadingAppInfoData; // @synthesize downloadingAppInfoData=_downloadingAppInfoData;
@property(nonatomic) _Bool hasDownload; // @synthesize hasDownload=_hasDownload;
@property(retain, nonatomic) WAPackagePredownloadInfo *packagePredownloadInfo; // @synthesize packagePredownloadInfo=_packagePredownloadInfo;
- (void).cxx_destruct;
- (void)onResUpdateFinish:(long long)arg1 resType:(unsigned int)arg2 subResType:(unsigned int)arg3;
- (void)checkWhatsNewImageUpdate;
- (void)saveWhatsImageVersion:(unsigned int)arg1;
- (unsigned int)getWhatsNewImageVersion;
- (id)pathOfWhatsNewImageVersion;
- (_Bool)presetupLaunchWithResponseString:(id)arg1 appId:(id)arg2;
- (_Bool)presetupContactWithResponseString:(id)arg1 userName:(id)arg2;
- (void)presetupDataWithContactResponseString:(id)arg1 launchResponseString:(id)arg2 userName:(id)arg3 appId:(id)arg4;
- (void)reportWithKey:(unsigned int)arg1;
- (void)onUpdateAppPkgComplete:(_Bool)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (_Bool)downloadPackageWithAppInfoData:(id)arg1 CDNURL:(id)arg2 patchURL:(id)arg3;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)onResponseDownloadPackageUrl:(id)arg1;
- (_Bool)getDownloadPackageUrl:(id)arg1;
- (void)resetOldExistVersionIfFileNotExist:(id)arg1;
- (id)getAppInfoDataWithPredownloadInfo:(id)arg1;
- (void)runDownloadProcessWithAppInfoData:(id)arg1;
- (void)checkDownloadPackage:(id)arg1;
- (void)resetDownloadState;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)onReceivePackagePredownloadNewXmlMsg:(id)arg1;
- (void)savePackagePredownloadInfo;
- (void)loadPackagePredownloadInfo;
- (id)pathOfPackagePredownloadInfo;
- (id)pathOfWhatsNewImage;
- (_Bool)hasWhatsNewImageFile;
- (id)getPackagePredownloadUserName;
- (void)onServiceEnterBackground;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

