//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface WAPackagePredownloadInfo : NSObject <PBCoding>
{
    unsigned int version;
    unsigned int reportId;
    unsigned int lastDownloadTime;
    unsigned int downloadCount;
    NSString *userName;
    NSString *appId;
    NSString *packageMd5;
}

+ (void)initialize;
@property(nonatomic) unsigned int downloadCount; // @synthesize downloadCount;
@property(nonatomic) unsigned int lastDownloadTime; // @synthesize lastDownloadTime;
@property(nonatomic) unsigned int reportId; // @synthesize reportId;
@property(retain, nonatomic) NSString *packageMd5; // @synthesize packageMd5;
@property(nonatomic) unsigned int version; // @synthesize version;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
- (void).cxx_destruct;
- (_Bool)isDataValid;
@property(readonly, copy) NSString *description;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

