//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"
#import "WAGameWhatsNewLoadingViewControllerDelegate.h"

@class NSString, WAWhatsNewInfo;

@interface WAWhatsNewMgr : MMService <IMsgExt, WAGameWhatsNewLoadingViewControllerDelegate, MMService>
{
    _Bool _isShowedWhatsNew;
    WAWhatsNewInfo *_whatsNewInfo;
}

@property(nonatomic) _Bool isShowedWhatsNew; // @synthesize isShowedWhatsNew=_isShowedWhatsNew;
@property(retain, nonatomic) WAWhatsNewInfo *whatsNewInfo; // @synthesize whatsNewInfo=_whatsNewInfo;
- (void).cxx_destruct;
- (void)onLoadingViewClickEnterWeAppBtn:(id)arg1;
- (void)reportWithKey:(unsigned int)arg1;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)onReceiveWhatsNewNewXmlMsg:(id)arg1;
- (void)markShowWhatsNew;
- (void)loadWhatsNewRecord;
- (id)pathOfWhatsNewRecord;
- (void)saveWhatsNewInfo;
- (void)loadWhatsNewInfo;
- (id)pathOfWhatsNewInfo;
- (_Bool)isInShowTime;
- (id)getWhatsNewUserName;
- (void)reportOpenWhatsNewFail;
- (void)showWeAppWhatsNewOnAboutWeChat:(id)arg1;
- (void)showWeAppWhatsNewWithLoadingView:(id)arg1;
- (void)showWhatsNewLoadingViewWithWindow:(id)arg1 whatsNewDelegate:(id)arg2;
- (_Bool)isNeedShowWhatsNewOnAboutWeChat;
- (_Bool)isNeedShowWhatsNew;
- (void)clearShowWhatsNew;
- (_Bool)hasShowWhatsNew;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

