//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString, WAWhatsNewConfig;

@interface WAWhatsNewInfo : NSObject <PBCoding>
{
    WAWhatsNewConfig *config;
}

+ (void)initialize;
@property(retain, nonatomic) WAWhatsNewConfig *config; // @synthesize config;
- (void).cxx_destruct;
- (_Bool)isOrientationLandscape;
@property(readonly, copy) NSString *description;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

