//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "KSAudioPlayerProtocol.h"

@class AVPlayer, KSSongInfo, NSString;

@interface MMKSLiveAudioPlayer : NSObject <KSAudioPlayerProtocol>
{
    _Bool _manualProcessInterrup;
    _Bool _pauseOnHeadPhoneOut;
    unsigned int _secondCacheCnt;
    KSSongInfo *_curSong;
    id <KSAudioPlayerDelegate> _delegate;
    unsigned long long _status;
    double _playTimeWithNoPause;
    AVPlayer *_player;
    double _cacheProgress;
    double _bufferTime;
    double _startTime;
}

@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double bufferTime; // @synthesize bufferTime=_bufferTime;
@property(nonatomic) double cacheProgress; // @synthesize cacheProgress=_cacheProgress;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) double playTimeWithNoPause; // @synthesize playTimeWithNoPause=_playTimeWithNoPause;
@property(readonly, nonatomic) unsigned int secondCacheCnt; // @synthesize secondCacheCnt=_secondCacheCnt;
@property(nonatomic) _Bool pauseOnHeadPhoneOut; // @synthesize pauseOnHeadPhoneOut=_pauseOnHeadPhoneOut;
@property(nonatomic) _Bool manualProcessInterrup; // @synthesize manualProcessInterrup=_manualProcessInterrup;
@property(readonly, nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) __weak id <KSAudioPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) KSSongInfo *curSong; // @synthesize curSong=_curSong;
- (void).cxx_destruct;
- (void)onPlayerItemFailedToPlayToEndTime:(id)arg1;
- (void)onPlayerDidFinishPlaying;
- (void)releasePlayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) double curTime;
@property(readonly, nonatomic) double duration;
- (unsigned long long)errType;
- (id)errDetail;
- (id)dataProviderDetail;
- (double)firstBufTime;
- (void)seek:(double)arg1;
- (void)resume;
- (void)pause;
- (void)internalStop;
- (void)stop;
- (_Bool)play:(id)arg1 seekTime:(double)arg2;
- (_Bool)play:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

