//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RenderStats : NSObject
{
    unsigned long long _firstFrameRenderTS;
    unsigned long long _blockCount;
    unsigned long long _blockTime;
    unsigned long long _totalBlockCount;
    unsigned long long _maxBlockDuration;
    unsigned long long _renderFrameCount;
}

@property(nonatomic) unsigned long long renderFrameCount; // @synthesize renderFrameCount=_renderFrameCount;
@property(nonatomic) unsigned long long maxBlockDuration; // @synthesize maxBlockDuration=_maxBlockDuration;
@property(nonatomic) unsigned long long totalBlockCount; // @synthesize totalBlockCount=_totalBlockCount;
@property(nonatomic) unsigned long long blockTime; // @synthesize blockTime=_blockTime;
@property(nonatomic) unsigned long long blockCount; // @synthesize blockCount=_blockCount;
@property(nonatomic) unsigned long long firstFrameRenderTS; // @synthesize firstFrameRenderTS=_firstFrameRenderTS;

@end

