//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TXIModule.h"

@class NSString;

@interface TXCModule : NSObject <TXIModule>
{
    NSString *_id;
}

- (void).cxx_destruct;
- (id)statusValueForKey:(long long)arg1;
- (_Bool)setStatusValue:(id)arg1 forKey:(long long)arg2;
- (id)getID;
- (void)clearID;
- (void)setID:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

