//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXDRApi : NSObject
{
}

+ (void)initCrashReport;
+ (void)txReportDAU:(int)arg1 withErrCode:(int)arg2 withErrInfo:(id)arg3;
+ (void)txReportDAU:(int)arg1;
+ (int)GetStatusReportInterval;
+ (void)ReportEvent40003:(id)arg1 withCode:(int)arg2 withCodeDesp:(id)arg3 withMoreMsg:(id)arg4;
+ (void)ReportEvent:(id)arg1 withCommandId:(int)arg2;
+ (void)SetEventIntValue:(id)arg1 withCommandId:(int)arg2 withKey:(id)arg3 withValue:(long long)arg4;
+ (void)SetEventValue:(id)arg1 withCommandId:(int)arg2 withKey:(id)arg3 withValue:(id)arg4;
+ (void)SetCommonValue:(id)arg1 withValule:(id)arg2;
+ (void)InitReportEvent:(id)arg1 withCommandId:(int)arg2 withModuleId:(int)arg3 withExtInfo:(id)arg4;
+ (id)CreateToken;
+ (void)SetAppVersion:(id)arg1;
+ (id)DeviceModelName;

@end

