//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TXIStatsCollection.h"

@class NSLock, NSMutableDictionary, NSObject<OS_dispatch_source>, NSString, TXCVideoEncoder;

@interface TXLivePushStatsCollection : NSObject <TXIStatsCollection>
{
    double _collectInterval;
    NSObject<OS_dispatch_source> *_timer;
    NSMutableDictionary *_stats;
    NSMutableDictionary *_fix;
    NSMutableDictionary *_last;
    long long _lastTimestamp;
    long long _lastNotify;
    long long _lastReport;
    NSLock *_lock;
    _Bool _isCollecting;
    _Bool _isReportBegin;
    int _audioSampleRate;
    int _videoWidth;
    int _videoHeight;
    int _videoBitrate;
    int _encodeType;
    id <TXINotifyDelegate> _notifyDelegate;
    id <TXIUploader> _uploader;
    TXCVideoEncoder *_encoder;
    NSString *_url;
}

@property(nonatomic) int encodeType; // @synthesize encodeType=_encodeType;
@property(nonatomic) int videoBitrate; // @synthesize videoBitrate=_videoBitrate;
@property(nonatomic) int videoHeight; // @synthesize videoHeight=_videoHeight;
@property(nonatomic) int videoWidth; // @synthesize videoWidth=_videoWidth;
@property(nonatomic) int audioSampleRate; // @synthesize audioSampleRate=_audioSampleRate;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) __weak TXCVideoEncoder *encoder; // @synthesize encoder=_encoder;
@property(nonatomic) __weak id <TXIUploader> uploader; // @synthesize uploader=_uploader;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
- (void).cxx_destruct;
- (void)setupStats;
- (long long)updateField:(id)arg1 value:(long long)arg2;
- (void)updateNetStats:(id)arg1 interval:(long long)arg2;
- (id)getSubStats;
- (void)collectStatus;
- (void)reportStatus;
- (void)reportEndEvt;
- (void)reportBeginEvt;
- (void)reportFailed;
- (long long)getValueByKey:(id)arg1;
- (id)getStats;
- (void)stop;
- (void)startWithInteral:(double)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

