//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TXICustomPreprocessDelegate.h"
#import "TXINotifyDelegate.h"

@class NSString, TXCLivePusher, TXLivePushConfig, UITextView;

@interface TXLivePush : NSObject <TXINotifyDelegate, TXICustomPreprocessDelegate>
{
    int _videoQuality;
    NSString *_rtmpURL;
    TXCLivePusher *_livePusher;
    UITextView *_statusView;
    UITextView *_evtLogView;
    TXLivePushConfig *_config;
    id <TXLivePushListener> _delegate;
    id <TXVideoCustomProcessDelegate> _videoProcessDelegate;
}

@property(nonatomic) __weak id <TXVideoCustomProcessDelegate> videoProcessDelegate; // @synthesize videoProcessDelegate=_videoProcessDelegate;
@property(nonatomic) __weak id <TXLivePushListener> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) TXLivePushConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)onDetectFacePoints:(id)arg1;
- (void)onTextureDestoryed;
- (unsigned int)onCustomPreprocess:(unsigned int)arg1 width:(long long)arg2 height:(long long)arg3;
- (void)onNotifyEvent:(int)arg1 withParams:(id)arg2;
- (void)showVideoDebugLog:(_Bool)arg1;
- (void)selectMotionTmpl:(id)arg1 inDir:(id)arg2;
- (void)setGreenScreenFile:(id)arg1;
- (_Bool)setReverbType:(long long)arg1;
- (void)setVideoQuality:(long long)arg1 adjustBitrate:(_Bool)arg2 adjustResolution:(_Bool)arg3;
- (int)getAdjustStrategyByBitrate:(_Bool)arg1 andResolution:(_Bool)arg2;
- (void)setAdjustStrategyByBitrate:(_Bool)arg1 andResolution:(_Bool)arg2;
- (_Bool)setBGMVolume:(float)arg1;
- (_Bool)setMicVolume:(float)arg1;
- (int)getMusicDuration:(id)arg1;
- (_Bool)resumeBGM;
- (_Bool)pauseBGM;
- (_Bool)stopBGM;
- (_Bool)playBGM:(id)arg1 withBeginNotify:(CDUnknownBlockType)arg2 withProgressNotify:(CDUnknownBlockType)arg3 andCompleteNotify:(CDUnknownBlockType)arg4;
- (_Bool)playBGM:(id)arg1;
- (void)setZoom:(double)arg1;
- (void)setFocusPosition:(struct CGPoint)arg1;
- (void)setSendAudioSampleBufferMuted:(_Bool)arg1;
- (void)sendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 withType:(long long)arg2;
- (void)sendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)sendCustomPCMData:(char *)arg1 len:(unsigned int)arg2;
- (void)setMute:(_Bool)arg1;
- (void)setRenderRotation:(int)arg1;
- (_Bool)toggleTorch:(_Bool)arg1;
- (void)setSpecialRatio:(float)arg1;
- (void)setFilter:(id)arg1;
- (void)setNoseSlimLevel:(float)arg1;
- (void)setFaceShortLevel:(float)arg1;
- (void)setChinLevel:(float)arg1;
- (void)setFaceVLevel:(float)arg1;
- (void)setFaceScaleLevel:(float)arg1;
- (void)setEyeScaleLevel:(float)arg1;
- (void)setBeautyStyle:(int)arg1 beautyLevel:(float)arg2 whitenessLevel:(float)arg3 ruddinessLevel:(float)arg4;
- (void)setMirror:(_Bool)arg1;
- (int)switchCamera;
- (void)stopPreview;
- (int)startPreview:(id)arg1;
- (_Bool)isPublishing;
- (void)resumePush;
- (void)pausePush;
- (void)stopPush;
- (int)startPush:(id)arg1;
@property(readonly, nonatomic) _Bool frontCamera;
@property(readonly, nonatomic) NSString *rtmpURL;
- (struct CGSize)getVideoSize:(struct CGSize)arg1;
- (void)applyConfig;
- (void)sendPushEvent:(int)arg1 withDescription:(id)arg2;
- (void)dealloc;
- (id)initWithConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

