//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WALoadingViewController.h"

#import "IWALocalCacheMgrExt.h"

@class UIButton, UIImageView, UILabel, UIView, WAWhatsNewInfo, WAWhatsNewStepHandler;

@interface WAGameWhatsNewLoadingViewController : WALoadingViewController <IWALocalCacheMgrExt>
{
    _Bool _hasClickEnterWeAppBtn;
    _Bool _hiddenBackGround;
    id <WAGameWhatsNewLoadingViewControllerDelegate> _whatsNewDelegate;
    WAWhatsNewInfo *_whatsNewInfo;
    WAWhatsNewStepHandler *_whatsNewHandler;
    unsigned long long _lockedOrientation;
    UIImageView *_logoView;
    UILabel *_sloganLabel;
    UIView *_totalProcessView;
    UIView *_currentProcessView;
    UIButton *_skipButton;
    UIImageView *_skipArrow;
    UIButton *_bgButton;
}

@property(retain, nonatomic) UIButton *bgButton; // @synthesize bgButton=_bgButton;
@property(retain, nonatomic) UIImageView *skipArrow; // @synthesize skipArrow=_skipArrow;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIView *currentProcessView; // @synthesize currentProcessView=_currentProcessView;
@property(retain, nonatomic) UIView *totalProcessView; // @synthesize totalProcessView=_totalProcessView;
@property(retain, nonatomic) UILabel *sloganLabel; // @synthesize sloganLabel=_sloganLabel;
@property(retain, nonatomic) UIImageView *logoView; // @synthesize logoView=_logoView;
@property(nonatomic) unsigned long long lockedOrientation; // @synthesize lockedOrientation=_lockedOrientation;
@property(nonatomic) _Bool hiddenBackGround; // @synthesize hiddenBackGround=_hiddenBackGround;
@property(nonatomic) _Bool hasClickEnterWeAppBtn; // @synthesize hasClickEnterWeAppBtn=_hasClickEnterWeAppBtn;
@property(retain, nonatomic) WAWhatsNewStepHandler *whatsNewHandler; // @synthesize whatsNewHandler=_whatsNewHandler;
@property(retain, nonatomic) WAWhatsNewInfo *whatsNewInfo; // @synthesize whatsNewInfo=_whatsNewInfo;
@property(nonatomic) __weak id <WAGameWhatsNewLoadingViewControllerDelegate> whatsNewDelegate; // @synthesize whatsNewDelegate=_whatsNewDelegate;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (void)unlockOrientation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)lockOrientation:(long long)arg1;
- (void)onCheckLocalPkg:(_Bool)arg1;
- (void)onUpdateAppPkgComplete:(_Bool)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 withAppInfoData:(id)arg3;
- (void)onReturn;
- (void)startEnterAppAnimation;
- (void)onClickSkipButton:(id)arg1;
- (void)onClickEnterWeAppButton:(id)arg1;
- (void)setProcessValue:(double)arg1;
- (void)setupUI;
- (void)showLandScapeSetupUI;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

