//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@interface WCPayGPPayNotifyConfirmView : MMUIView
{
    id <WCPayGPPayNotifyConfirmViewDelegate> _delegate;
    MMUIView *_contentView;
}

@property(retain, nonatomic) MMUIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <WCPayGPPayNotifyConfirmViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onConfirm;
- (void)onCancel;
- (void)hideView;
- (void)showView;
- (id)genNewBigButton;
- (void)setupContentView;
- (void)setupSubview;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

@end

