//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "WCBaseInfoItemDelegate.h"

@class NSString, UIButton, UIView, WCPayTenpayPasswordCtrlItem;

@interface WCPayNewPwdViewController : WCPayBaseViewController <WCBaseInfoItemDelegate>
{
    id <WCPayNewPwdViewControllerDelegate> m_delegate;
    NSString *_vcTitle;
    NSString *_vcTips;
    UIView *_verifyPasswordView;
    UIView *_verifyTouchIdView;
    UIView *_currentView;
    UIButton *_footerButton;
    WCPayTenpayPasswordCtrlItem *_passwordTextField;
}

@property(retain, nonatomic) WCPayTenpayPasswordCtrlItem *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) UIButton *footerButton; // @synthesize footerButton=_footerButton;
@property(retain, nonatomic) UIView *currentView; // @synthesize currentView=_currentView;
@property(retain, nonatomic) UIView *verifyTouchIdView; // @synthesize verifyTouchIdView=_verifyTouchIdView;
@property(retain, nonatomic) UIView *verifyPasswordView; // @synthesize verifyPasswordView=_verifyPasswordView;
@property(retain, nonatomic) NSString *vcTips; // @synthesize vcTips=_vcTips;
@property(retain, nonatomic) NSString *vcTitle; // @synthesize vcTitle=_vcTitle;
- (void).cxx_destruct;
- (void)clearPwdInput;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)showVerifyPwdCtrlWithTitle:(id)arg1 tips:(id)arg2;
- (void)onCancelVerify;
- (void)initNavigationBar;
- (void)refreshViewWithData:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)setDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

