//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WSReportHelper : NSObject
{
}

+ (void)reportWebviewError:(int)arg1 scene:(unsigned int)arg2 h5version:(unsigned int)arg3 errorCode:(int)arg4 errorMsg:(id)arg5;
+ (void)ReportUnRecognizedJSApi;
+ (void)ReportWSLoadH5Fail;
+ (void)ReportAccessDownloadH5;
+ (void)ReportAccessDefaultH5;

@end

