//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "WAVideoPlayerCoreDelegate.h"
#import "WSPlayerMaskViewDelegate.h"

@class AVPlayerItemVideoOutput, MMProgressViewEx, MMUILabel, MPVolumeView, NSString, UIButton, UIImage, UIImageView, WAScreenBrightnessStateView, WAVideoPlayerCore, WCNetworkMediaSlider, WSPlayerMaskView;

@interface WSStreamPlayerView : UIView <WAVideoPlayerCoreDelegate, UIGestureRecognizerDelegate, WSPlayerMaskViewDelegate>
{
    _Bool _disableScroll;
    _Bool _lockSlider;
    _Bool _touchesProgressMoved;
    _Bool _useCustomDuration;
    _Bool _customThumb;
    unsigned int _pauseTemp;
    long long _panDirection;
    _Bool _adjustVolume;
    WAScreenBrightnessStateView *_bvstatusView;
    MPVolumeView *_airPlayBtn;
    double _totalDuration;
    _Bool _bShouldBeFirstFrame;
    _Bool _customCache;
    _Bool _autoPlay;
    _Bool _needUpdateEvent;
    _Bool _enablePageGesture;
    _Bool _loop;
    _Bool _isShowReplayBtnStatus;
    unsigned int _videoId;
    unsigned int _videoFileSize;
    long long _orientation;
    id <WSVideoPlayerViewDelegate> _videoDelagate;
    NSString *_userData;
    WAVideoPlayerCore *_mediaCore;
    UIView *_bottomView;
    MMUILabel *_currentLabel;
    WCNetworkMediaSlider *_progressSlider;
    MMUILabel *_durationLabel;
    UIButton *_playBtn;
    UIButton *_fullBtn;
    UIButton *_voiceButton;
    MMProgressViewEx *_loadingView;
    UIView *_coverView;
    MMUILabel *_centerTime;
    UIImageView *_thumbImage;
    NSString *_videoGravity;
    UIImage *_snapImage;
    AVPlayerItemVideoOutput *_snapshotOutput;
    WSPlayerMaskView *_playerMaskView;
    NSString *_newestNetType;
    UIView *_topView;
    UIButton *_topBackBtn;
    UIButton *_replayBtn;
    UIButton *_replayLabelBtn;
    UIView *_controlMaskView;
    NSString *_videoUrl;
    unsigned long long _clickPlayTimestamp;
    unsigned long long _videoBeginPlayTimestamp;
    struct CGSize _videoSize;
    struct CGRect _rect;
}

@property(nonatomic) unsigned long long videoBeginPlayTimestamp; // @synthesize videoBeginPlayTimestamp=_videoBeginPlayTimestamp;
@property(nonatomic) unsigned long long clickPlayTimestamp; // @synthesize clickPlayTimestamp=_clickPlayTimestamp;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(retain, nonatomic) UIView *controlMaskView; // @synthesize controlMaskView=_controlMaskView;
@property(nonatomic) _Bool isShowReplayBtnStatus; // @synthesize isShowReplayBtnStatus=_isShowReplayBtnStatus;
@property(retain, nonatomic) UIButton *replayLabelBtn; // @synthesize replayLabelBtn=_replayLabelBtn;
@property(retain, nonatomic) UIButton *replayBtn; // @synthesize replayBtn=_replayBtn;
@property(retain, nonatomic) UIButton *topBackBtn; // @synthesize topBackBtn=_topBackBtn;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) NSString *newestNetType; // @synthesize newestNetType=_newestNetType;
@property(retain, nonatomic) WSPlayerMaskView *playerMaskView; // @synthesize playerMaskView=_playerMaskView;
@property(retain, nonatomic) AVPlayerItemVideoOutput *snapshotOutput; // @synthesize snapshotOutput=_snapshotOutput;
@property(retain, nonatomic) UIImage *snapImage; // @synthesize snapImage=_snapImage;
@property(copy, nonatomic) NSString *videoGravity; // @synthesize videoGravity=_videoGravity;
@property(retain, nonatomic) UIImageView *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(retain, nonatomic) MMUILabel *centerTime; // @synthesize centerTime=_centerTime;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) MMProgressViewEx *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property(retain, nonatomic) UIButton *fullBtn; // @synthesize fullBtn=_fullBtn;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) MMUILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) WCNetworkMediaSlider *progressSlider; // @synthesize progressSlider=_progressSlider;
@property(retain, nonatomic) MMUILabel *currentLabel; // @synthesize currentLabel=_currentLabel;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(retain, nonatomic) WAVideoPlayerCore *mediaCore; // @synthesize mediaCore=_mediaCore;
@property(nonatomic) unsigned int videoFileSize; // @synthesize videoFileSize=_videoFileSize;
@property(nonatomic) _Bool loop; // @synthesize loop=_loop;
@property(nonatomic) _Bool enablePageGesture; // @synthesize enablePageGesture=_enablePageGesture;
@property(nonatomic) _Bool needUpdateEvent; // @synthesize needUpdateEvent=_needUpdateEvent;
@property(copy, nonatomic) NSString *userData; // @synthesize userData=_userData;
@property(nonatomic) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(nonatomic) _Bool customCache; // @synthesize customCache=_customCache;
@property(nonatomic) unsigned int videoId; // @synthesize videoId=_videoId;
@property(nonatomic) __weak id <WSVideoPlayerViewDelegate> videoDelagate; // @synthesize videoDelagate=_videoDelagate;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void).cxx_destruct;
- (void)volumeChanged:(id)arg1;
- (void)onMaskViewTopBackBtnClick;
- (void)clearPlayerMaskView;
- (void)onCancelBtnClick;
- (void)onTipBtnClickForRetryPlay;
- (void)onTipBtnClickForContinuePlay;
- (void)onTipBtnClickForReplay;
- (void)showMaskWithTip:(id)arg1 btnType:(unsigned long long)arg2 showCancelBtn:(_Bool)arg3;
- (void)onNetWorkChangeToNetType:(id)arg1;
- (_Bool)isForground;
- (void)setMuted:(_Bool)arg1;
- (void)setPlayBackRate:(float)arg1;
- (long long)pauseCount;
- (void)pauseTemp:(_Bool)arg1;
- (void)pausePlayAndLoading;
- (void)routeChange:(id)arg1;
- (id)drawInRectAspectFill:(id)arg1;
- (id)getCurrentSnapshot;
- (void)setObjectFit:(long long)arg1;
- (void)resetSliderLock;
- (void)hideBrightnessStatusView;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)disableScroll:(_Bool)arg1;
- (void)setDuration:(double)arg1;
- (void)resizeThumbImage;
- (void)onTopBackBtnClick;
- (void)onVoiceButtonClick;
- (void)onFullClick;
- (void)disableFull;
- (void)enableFull;
- (void)enableFullScreen:(_Bool)arg1;
- (long long)fullscreenOrientation;
- (void)onCurrentTimeUpdate:(double)arg1;
- (void)onTotalTimeUpdate:(double)arg1;
- (void)onCacheUpdate:(double)arg1;
- (void)onLoadingEnd;
- (void)onLoadingBegin;
- (void)onVideoPlayEnd;
- (void)onNetWorkError:(long long)arg1 errorMsg:(id)arg2;
- (void)onStateChange:(long long)arg1;
- (void)pause;
- (void)seek:(unsigned int)arg1;
- (void)stop;
- (void)play:(_Bool)arg1;
- (void)onReplay;
- (void)onReplayBtnClick;
- (void)onPlayClick;
- (void)onSliderChange;
- (void)onSliderTouchUp;
- (void)onSliderTouchDown;
- (_Bool)isShowReplayBtn;
- (void)hideControlViews;
- (void)showControlViews;
- (void)catchTap:(id)arg1;
- (_Bool)isPlaying;
- (id)timeFormat:(int)arg1;
- (void)updateSubviews:(struct CGSize)arg1;
- (void)horizontalMoveEnd;
- (void)horizontalMoved:(double)arg1;
- (void)verticalMoved:(double)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)panGestureControl:(id)arg1;
- (void)setVideoFrame:(struct CGRect)arg1;
- (_Bool)isFullScreen;
- (void)updateThumbImage;
- (void)updateLiveSize;
- (void)initMediaCore:(id)arg1 initialTime:(unsigned int)arg2;
- (void)setVideoPath:(id)arg1 initialTime:(unsigned int)arg2;
- (void)setVideoThumbImage:(id)arg1;
- (void)setVideoThumb:(id)arg1;
- (void)dealloc;
- (void)showReplayBtn;
- (void)tryInitReplayViews;
- (id)initWithThumb:(id)arg1 frame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

