//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray;

@interface WXGGetCallStackReportHandler : NSObject
{
    NSMutableArray *m_binaryImages;
    NSDictionary *m_systemInfo;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)getReportJsonDataWithCallStackArray:(struct KSStackCursor **)arg1 callStackCount:(unsigned long long)arg2 withReportID:(id)arg3 withDumpType:(unsigned long long)arg4 withScene:(id)arg5;
- (id)getReportJsonDataWithCallStackArray:(struct KSStackCursor **)arg1 callStackCount:(unsigned long long)arg2 withReportID:(id)arg3 withDumpType:(unsigned long long)arg4;
- (void)setupBinaryImages;
- (id)init;

@end

